name: build and test
on:
  push:
    branches: [ "3.X.X-Branch" ]
  pull_request:
    branches: [ "3.X.X-Branch" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci  # 'npm ci' is recommended in CI/CD to install exact version of dependencies from package-lock.json
    - name: Build
      run: npm run build  # Using your npm script for build instead of direct webpack call
    - name: Lint
      run: npm run lint  # Add your lint script to the CI/CD pipeline
    - name: Test
      run: npm run test  # Add your test script to the CI/CD pipeline
