name: build
on:
  push:
    branches: [ "3.X.X-Branch" ]
  pull_request:
    branches: [ "3.X.X-Branch" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # This path is specific to npm
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # - name: Lint
    #   run: npm run lint

    - name: Build
      run: npm run build 
      
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🧑‍💻 ${{ github.actor }} pushed a change:
          
            *Repository*: [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Branch*: `${{ github.ref }}`.split('/').pop()
          
            *Commit*:
            - Message: `${{ github.event.commits[0].message }}`
            - SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          
            *Workflow*: `${{ github.workflow }}`
            *Action*: `${{ github.action }}`
            *Event*: `${{ github.event.name }}`
          
            ***Check the latest changes*** 💥:
            👀 [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            🛠️ [Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            
    - name: Send Telegram notification on failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            🧑‍💻 ${{ github.actor }} caused a failed build:
          
            *Repository*: [${{ github.repository }}](https://github.com/${{ github.repository }})
            *Branch*: `${{ github.ref }}`.split('/').pop()
          
            *Commit*:
            - Message: `${{ github.event.commits[0].message }}`
            - SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          
            *Workflow*: `${{ github.workflow }}`
            *Action*: `${{ github.action }}`
            *Event*: `${{ github.event.name }}`
          
            ***Check the latest changes*** 💥:
            👀 [View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            🛠️ [Action Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
